# Generated by Django 4.1.5 on 2023-01-12 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('details', models.CharField(max_length=255)),
                ('reviews', models.IntegerField()),
                ('stars', models.IntegerField()),
            ],
        ),
    ]
