# Generated by Django 4.1.5 on 2023-01-12 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='image',
            field=models.ImageField(default='', upload_to='', verbose_name='images/'),
            preserve_default=False,
        ),
    ]
